# Generated by Django 5.1.1 on 2024-10-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Penelitian', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='penelitiandosen',
            name='jurnal_conference',
            field=models.CharField(default='Unknown', max_length=250),
        ),
        migrations.AddField(
            model_name='penelitiandosen',
            name='nama_dosen',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='penelitiandosen',
            name='tahun_publikasi',
            field=models.IntegerField(null=True),
        ),
    ]
