# Generated by Django 5.1.1 on 2024-10-21 10:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Penelitian', '0003_remove_penelitiandosen_jurnal_conference_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopikPenelitian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('penelitiandosen_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Penelitian.penelitiandosen')),
            ],
        ),
    ]
