# Generated by Django 5.1.1 on 2024-10-21 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Penelitian', '0004_topikpenelitian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topikpenelitian',
            name='penelitiandosen_id',
        ),
        migrations.AddField(
            model_name='penelitiandosen',
            name='topikpenelitian_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Penelitian.topikpenelitian'),
        ),
    ]
