# Generated by Django 5.1.1 on 2024-10-22 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Penelitian', '0006_katakunci'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KataKunci',
        ),
    ]
