# Generated by Django 5.1.1 on 2024-11-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Penelitian', '0007_delete_katakunci'),
    ]

    operations = [
        migrations.AddField(
            model_name='penelitiandosen',
            name='scopus_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='penelitiandosen',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Non-Active', 'Non-Active')], default='Active', max_length=10),
        ),
    ]
