# Generated by Django 5.1.1 on 2024-11-06 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dosen', '0004_dosen_fotodosen'),
        ('Penelitian', '0008_penelitiandosen_scopus_id_penelitiandosen_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='penelitiandosen',
            name='dosen',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Dosen.dosen'),
        ),
    ]
