# Generated by Django 5.1.1 on 2024-11-06 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Penelitian', '0009_penelitiandosen_dosen'),
    ]

    operations = [
        migrations.AddField(
            model_name='penelitiandosen',
            name='author_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
