# Generated by Django 5.1.1 on 2024-11-07 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Penelitian', '0010_penelitiandosen_author_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='penelitiandosen',
            name='scopus_id',
        ),
    ]
