# Generated by Django 5.1.2 on 2024-11-07 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Penelitian', '0013_alter_penelitiandosen_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penelitiandosen',
            name='abstract',
            field=models.CharField(max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='penelitiandosen',
            name='judul',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
