# Generated by Django 5.1.2 on 2024-11-07 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Penelitian', '0014_alter_penelitiandosen_abstract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penelitiandosen',
            name='abstract',
            field=models.CharField(max_length=5000, null=True),
        ),
    ]
