# Generated by Django 5.1.1 on 2024-10-22 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NamaDosen', models.CharField(max_length=50)),
                ('EmailAkun', models.CharField(max_length=30)),
                ('NoTelepon', models.IntegerField(null=True)),
                ('Keahlian', models.CharField(max_length=1)),
            ],
        ),
    ]
