# Generated by Django 5.1.1 on 2024-11-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dosen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosen',
            name='NIDNDosen',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
