# Generated by Django 5.1.1 on 2024-11-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dosen', '0002_dosen_nidndosen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosen',
            name='EmailAkun',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dosen',
            name='NamaDosen',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
