# Generated by Django 5.1.1 on 2024-11-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dosen', '0003_alter_dosen_emailakun_alter_dosen_namadosen'),
    ]

    operations = [
        migrations.AddField(
            model_name='dosen',
            name='FotoDosen',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
