# Generated by Django 5.1.1 on 2024-11-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dosen', '0004_dosen_fotodosen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dosen',
            name='NamaDosen',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
