# Generated by Django 5.1.1 on 2024-11-15 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dosen', '0005_alter_dosen_namadosen'),
        ('Penelitian', '0016_remove_penelitiandosen_topikpenelitian_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dosen',
            name='Keahlian',
        ),
        migrations.AddField(
            model_name='dosen',
            name='Kepakaran_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Kepakaran_1', to='Penelitian.topikpenelitian'),
        ),
        migrations.AddField(
            model_name='dosen',
            name='Kepakaran_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Kepakaran_2', to='Penelitian.topikpenelitian'),
        ),
        migrations.AddField(
            model_name='dosen',
            name='Kepakaran_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Kepakaran_3', to='Penelitian.topikpenelitian'),
        ),
    ]
