# Generated by Django 5.1.1 on 2024-10-20 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idePenelitian', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PenelitianDosen',
        ),
    ]
