# Generated by Django 5.1.1 on 2024-10-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('idePenelitian', '0002_delete_penelitiandosen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Histori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
